syscall: generate manual pipe(int[2]) stub (gcc13)
GCC introduced an array-parameter diagnostic that causes the mismatch
between pipe(int*) (the syscall stub/implementation) and pipe(int[2])
(the declaration in unistd.h) to raise an error:

build-scons/i586-gcc/user/newlib_syscall_stubs.tpl.c:1780:15: error: argument 1 of type 'int *' declared as a pointer [-Werror=array-parameter=]
 1780 | int pipe(int* fildes) { return _pipe_r(_REENT, fildes); }
      |          ~~~~~^~~~~~
In file included from .../include/unistd.h:4,
                 from .../include/apos/syscall_decls.h:33,
                 from build-scons/i586-gcc/user/newlib_syscall_stubs.tpl.c:13:
.../include/sys/unistd.h:45:14: note: previously declared as an array 'int[2]'
   45 | int pipe(int fds[2]);
      |          ~~~~^~~~~~

Rather than deal with the complexity of supporting array-typed arguments
for the syscall generators, this just adds a manual stub for pipe()
specifically to sidestep (but also allow us to keep the new diagnostic).