test: fix empty EMPTY_MMAP() arrays in tests (gcc13)
These arrays passed when no mmap entries are expected are bogus.  They
are never read, so it doesn't cause any problems, but GCC now flags:

test/mmap_test.c: In function 'do_mmap_test':
test/mmap_test.c:755:3: error: 'EXPECT_MMAP' accessing 12 bytes in a region of size 0 [-Werror=stringop-overflow=]
  755 |   EXPECT_MMAP(0, (emmap_t[]){});
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/mmap_test.c:755:3: note: referencing argument 2 of type 'emmap_t[0]'
test/mmap_test.c:79:13: note: in a call to function 'EXPECT_MMAP'
   79 | static void EXPECT_MMAP(int num_entries, emmap_t expected[]) {
      |             ^~~~~~~~~~~
cc1: all warnings being treated as errors

Rather than change EXPECT_MMAP() to take a pointer (which disables this
check), add a dummy one-entry mmap constant to use in these tests.