vfs: split up rename tests
This takes rename_testA from a stack frame of 13k(!) down to no part
large than ~3k (still pretty big).  This was causing occasional stack
overflows when an interrupt would fire during the rename test.  For
comparison, they are now around the same size as the combined test
functions were previously under GCC.

Previously:
$ clang -c -Wall -Wextra -Werror -Wundef -std=gnu11 -Wno-unused-parameter -Wno-error=unused-function -Wstrict-prototypes -g3 -gdwarf-2 -target i586-pc-apos -fdebug-macro -nostdlib -ffreestanding -mno-mmx -mno-sse -Wno-self-assign -D__APOS_BUILDING_IN_TREE__=1 -D__APOS_BUILDING_KERNEL__=1 -Iarchs/x86-common -I. -Iarchs/i586 -Iarchs/common -Ibuild-scons/i586-clang -I. test/vfs_test.c -Wframe-larger-than=1 -ferror-limit=0 |& grep 'error: stack frame size' | grep rename_test

test/vfs_test.c:5967:13: error: stack frame size of 144 bytes in function 'rename_test'
test/vfs_test.c:4931:13: error: stack frame size of 13332 bytes in function 'rename_testA'
test/vfs_test.c:5519:13: error: stack frame size of 6580 bytes in function 'rename_testB'

After:
test/vfs_test.c:5999:13: error: stack frame size of 156 bytes in function 'rename_test'
test/vfs_test.c:4937:13: error: stack frame size of 1268 bytes in function 'rename_testA'
test/vfs_test.c:4990:13: error: stack frame size of 1404 bytes in function 'rename_testB'
test/vfs_test.c:5050:13: error: stack frame size of 3292 bytes in function 'rename_testC'
test/vfs_test.c:5185:13: error: stack frame size of 2132 bytes in function 'rename_testD'
test/vfs_test.c:5268:13: error: stack frame size of 1444 bytes in function 'rename_testE'
test/vfs_test.c:5326:13: error: stack frame size of 1412 bytes in function 'rename_testF'
test/vfs_test.c:5384:13: error: stack frame size of 1868 bytes in function 'rename_testG'
test/vfs_test.c:5460:13: error: stack frame size of 1908 bytes in function 'rename_testH'
test/vfs_test.c:5546:13: error: stack frame size of 2204 bytes in function 'rename_testI'
test/vfs_test.c:5649:13: error: stack frame size of 2788 bytes in function 'rename_testJ'
test/vfs_test.c:5727:13: error: stack frame size of 2796 bytes in function 'rename_testK'

Example stack overflow (caught with as-yet-unsubmitted stack overflow
protection patch):
Thread 8 (crashing):
 #0 0xc0347a14 in internal_timer_handler() [timer.c:101]
 #1 0xc0341a76 in irq_handler() [irq.c:130]
 #2 0xc0341091 in int_handler() [interrupts.c:234]
 #3 0xc0341d97 in _int_handlers_end() [isr.s:127]
 #4 0xc0341c8b in int32() [isr.s:77]
 #5 0xc01143bd in restore_interrupts() [interrupts.h:52]
 #6 0xc01154b1 in kmutex_assert_is_held() [kthread.c:405]
 #7 0xc010faf8 in block_cache_get_internal() [block_cache.c:332]
 #8 0xc010f4e3 in block_cache_get() [block_cache.c:422]
 #9 0xc012b61d in ext2_block_put() [ext2fs.c:59]
 #10 0xc01283bc in dirent_iterate() [ext2_ops.c:407]
 #11 0xc01280ab in lookup_internal() [ext2_ops.c:908]
 #12 0xc012481d in ext2_lookup() [ext2_ops.c:1294]
 #13 0xc01250af in ext2_rmdir() [ext2_ops.c:1447]
 #14 0xc011e671 in vfs_rename_unique() [vfs.c:1232]
 #15 0xc011d993 in vfs_rename() [vfs.c:1064]
 #16 0xc0308af5 in rename_testA() [vfs_test.c:5224]
 #17 0xc02e148f in rename_test() [vfs_test.c:5968]
 #18 0xc0285adb in vfs_test() [vfs_test.c:6704]
 #19 0xc012cb34 in do_test_cmd() [kernel_tests.c:165]
 #20 0xc0113cf7 in proc_fork_trampoline() [fork.c:41]
PANIC: Kernel double fault